server:
# ???????? 8888
  port: 3344
spring:
  application:
    name: cloud-config-center #???Eureka????????
  cloud:
    config:
      server:
        git:
      # Gitee???git????
          uri: https://github.com/shiro-maki/L.Tang
#????
          search-paths: /cloud-demo-1/config
# ????
          label: main
# ???????????
  #    username: xXXX
  #   password: xxxx

eureka:
  client:
    service-url:
      #??????????
      defaultZone: http://127.0.0.1:8000/eureka

