server:
  port: 80


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka

zuul:
  routes:
    damai-order: /order/**
    damai-user: /user/**
    defaultURL:
      path: /**
      serviceId: damai-index

  #敏感http头, '' 表示不过滤
  sensitive-headers: ''