server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
    instance-info-replication-interval-seconds: 3
    registry-fetch-interval-seconds: 3

feign:
  hystrix:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
        
myinfo:
    name: lisi
    age: 22
    email: 8888888@qq.com