demo.name: ycinfo
#demo.enable: true

server.port: 80

upload:
  enable: true
  mappings:
    - webPath: image
      diskPath: D:/_文件柜/132/1001/image/
    - webPath: doc
      diskPath: D:/_文件柜/132/1001/doc/

login:
  enable: true
  table-user: user
  column-name: username
  column-pwd: password
  column-email: email
  user-class-name: com.example.springbootdemo1.bean.User
  # 扩展字段 sha
  encryption: md5
  resources:
    - /a.html
    - /changePwd

spring:
  datasource:
    url: jdbc:mysql:///cz21-s2-ply-damai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a
  mail:
    # 邮箱服务器地址
    host: smtp.qq.com
    # 用户名
    username: 306529917@qq.com
    # 密码
    password: sijvkqoqqogpbgjh
    default-encoding: UTF-8

# 发送人的邮箱地址
mail:
  fromMail:
    addr: 306529917@qq.com

vcode:
  # 要拦截并且验证资源路径
  resources:
    - /login/login
    - /login/changePwd