server:
  port: 8002

spring:
  application:
    name: cloud-user

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
    instance-info-replication-interval-seconds: 3
    registry-fetch-interval-seconds: 3

---
spring:
  profiles: user8005

server:
  port: 8005

---
spring:
  profiles: user8006

server:
  port: 8006

